# Generated by Django 3.2.12 on 2024-12-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dest_input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_category', models.CharField(max_length=30)),
                ('dest_image', models.ImageField(upload_to='')),
                ('dest_desc', models.TextField()),
                ('dest_tips', models.TextField()),
            ],
        ),
    ]
