# Generated by Django 3.2.12 on 2024-12-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_dest_input_dest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dest_input',
            name='dest_tip1',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dest_input',
            name='dest_tip2',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dest_input',
            name='dest_tip3',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dest_input',
            name='dest_tips',
            field=models.TextField(default='un'),
        ),
    ]
