# Generated by Django 3.2.12 on 2024-12-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20241203_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='dest_input',
            name='dest_title',
            field=models.CharField(default='TITLE', max_length=50),
        ),
    ]
