# Generated by Django 3.2.12 on 2024-12-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_dest_input_dest_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='dest_input',
            name='dest_tip4',
            field=models.TextField(default='BEST OF LUCK'),
        ),
        migrations.AddField(
            model_name='dest_input',
            name='dest_tip5',
            field=models.TextField(default='HAVE A GREAT TRIP'),
        ),
    ]
