# Generated by Django 3.2.12 on 2025-01-11 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_auto_20250110_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='dest_category',
            field=models.CharField(default='un', max_length=30),
        ),
        migrations.AlterField(
            model_name='destination',
            name='dest_image',
            field=models.ImageField(upload_to='static'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='dest_title',
            field=models.CharField(default='TITLE', max_length=50),
        ),
        migrations.AlterField(
            model_name='destination',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SavedDestination',
        ),
    ]
