# Generated by Django 3.2.12 on 2025-01-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20250111_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='dest_category',
        ),
        migrations.AlterField(
            model_name='destination',
            name='dest_image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='destination',
            name='dest_title',
            field=models.CharField(max_length=255),
        ),
    ]
